name: Set up languages
description: Set up ruby, javascript, and dependencies
runs:
  using: composite
  steps:
    - name: Cleanup gemfile
      uses: ./.github/actions/cleanup-gemfile

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: cbv

    - name: Install Dependencies
      shell: bash
      working-directory: cbv
      run: bundle install

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version-file: 'cbv/.node-version'
        cache-dependency-path: 'cbv/yarn.lock'
        cache: 'yarn'

    - name: Install yarn dependencies
      shell: bash
      working-directory: cbv
      run: yarn install --frozen-lockfile
