name: Set up languages
description: Set up ruby, javascript, and dependencies
runs:
  using: composite
  steps:
    - name: Cleanup gemfile
      uses: ./.github/actions/cleanup-gemfile

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: app

    - name: Install Dependencies
      shell: bash
      working-directory: app
      run: bundle install

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - name: Install npm dependencies
      shell: bash
      run: npm install --frozen-lockfile
      working-directory: app
