name: Set up languages
description: Set up ruby, javascript, and dependencies
runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: app
        bundler-cache: true

    - name: Restore bootsnap cache
      uses: actions/cache@v4
      with:
        path: app/tmp/cache/bootsnap
        key: bootsnap-${{ runner.os }}-${{ hashFiles('app/Gemfile.lock') }}-${{ github.sha }}
        restore-keys: |
          bootsnap-${{ runner.os }}-${{ hashFiles('app/Gemfile.lock') }}-

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version-file: 'app/.node-version'
        cache-dependency-path: 'app/package-lock.json'
        cache: 'npm'

    - name: Install npm dependencies
      shell: bash
      working-directory: app
      run: npm install --frozen-lockfile
