# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/app" # location of dockerfile
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "bundler"
    directory: "/app" # location of Gemfile
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "direct"   # only update direct dependencies
    ignore:
      - dependency-name: "rails"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "puma"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "ruby"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "terraform"
    directory: "/infra" # path to your Terraform configs (adjust if needed)
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"