network.globalExclusions.exclusions(0).exclusion.name=Search
network.globalExclusions.exclusions(0).exclusion.enabled=true
network.globalExclusions.exclusions(0).exclusion.value=/.*\/(?:.{2}\/)?cbv\/employer_search\?authenticity\_token.*/gm

network.globalExclusions.exclusions(1).exclusion.name=Sitemap
network.globalExclusions.exclusions(1).exclusion.enabled=true
network.globalExclusions.exclusions(1).exclusion.value=/.*sitemap.xml/gm
