- id: la_ldh
  agency_name: Department of Health
  agency_contact_website: https://ldh.la.gov/renew-medicaid
  agency_missing_employers_website: https://ldh.la.gov/renew-medicaid
  agency_domain: <%= ENV["LA_LDH_DOMAIN_NAME"] %>
  # caseworker_feedback_form: n/a
  logo_path: ldh_logo.svg
  default_origin: sms
  pinwheel:
    environment: <%= ENV["LA_LDH_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["LA_LDH_ARGYLE_ENVIRONMENT"] %>
  transmission_method: <%= ENV.fetch("LA_LDH_TRANSMISSION_METHOD", "json") %>
  transmission_method_configuration:
    json_api_url: <%= ENV["LA_LDH_INCOME_REPORT_URL"] %>
    pdf_api_url: <%= ENV["LA_LDH_PDF_API_URL"] %>
    silently_retry_error_codes:
      - 403
      - 408
      - 502
    custom_headers:
      X-Gateway-APIKey: <%= ENV["LA_LDH_INCOME_REPORT_APIKEY"] %>
      AccountCode: <%= ENV["LA_LDH_INCOME_REPORT_ACCOUNTCODE"] %>
    include_report_pdf: <%= ENV["LA_LDH_INCLUDE_REPORT_PDF"] %>
  caseworker_fallback_email: <%= ENV["LA_LDH_CASEWORKER_FALLBACK_EMAIL"] %>
  staff_portal_enabled: false
  pilot_ended: <%= ENV["LA_LDH_PILOT_ENABLED"] != "true" %>
  # sso:
  #   client_id:     <%= ENV["AZURE_LA_LDH_CLIENT_ID"] %>
  #   client_secret: <%= ENV["AZURE_LA_LDH_CLIENT_SECRET"] %>
  #   tenant_id:     <%= ENV["AZURE_LA_LDH_TENANT_ID"] %>
  #   scope: "openid"
  #   name: "la_ldh"
  pay_income_days:
    w2: 90
    gig: 90
  invitation_valid_days: 14
  weekly_report:
    recipient: <%= ENV['LA_LDH_WEEKLY_REPORT_RECIPIENTS'] %>
    report_variant: flows
  applicant_attributes:
    case_number:
      required: false
    date_of_birth:
      required: true
      redaction_type: date
    doc_id:
      required: false

- id: nh_dhhs
  agency_name: Department of Health and Human Services
  agency_contact_website: https://www.dhhs.nh.gov/
  agency_missing_employers_website: https://www.dhhs.nh.gov/programs-services/medicaid/medicaid-eligibility-unknown-employer
  agency_domain: <%= ENV["NH_DHHS_DOMAIN_NAME"] %>
  logo_path: nh_dhhs_logo.png
  caseworker_feedback_form: https://docs.google.com/forms/d/e/1FAIpQLSfrUiz0oWE5jbXjPfl-idQQGPgxKplqFtcKq08UOhTaEa2k6A/viewform
  pinwheel:
    environment: <%= ENV["SANDBOX_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["SANDBOX_ARGYLE_ENVIRONMENT"] %>
  transmission_method: sftp
  transmission_method_configuration:
    user: <%= ENV['NH_DHHS_SFTP_USER'] %>
    private_key: <%= ENV['NH_DHHS_SFTP_PRIVATE_KEY'].inspect %>
    url: <%= ENV['NH_DHHS_SFTP_URL'] %>
    sftp_directory: <%= ENV['NH_DHHS_SFTP_DIRECTORY'] %>
    pdf_filename_format: CBV_%{case_number}_%{consent_timestamp}_%{confirmation_code}
  staff_portal_enabled: true
  pilot_ended: false
  generic_links_disabled: true
  sso:
    client_id: <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id: <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "sandbox"
  pay_income_days:
    w2: 90
    gig: 90
  application_reporting_months: 2
  invitation_valid_days: 30
  weekly_report:
    recipient: ffs-eng@navapbc.com
  applicant_attributes:
    first_name:
      required: true
      redaction_type: string
    middle_name:
      redaction_type: string
    last_name:
      required: true
      redaction_type: string
    case_number:
      required: true
    date_of_birth:
      required: true
      redaction_type: date
  activity_types:
    education: true
    community_service: true
    work_programs: true
    employment: true

- id: sandbox
  agency_name: Test Agency
  agency_contact_website: https://www.example.com/contact
  agency_missing_employers_website: https://www.example.com/contact
  agency_domain: <%= ENV["SANDBOX_DOMAIN_NAME"] %>
  caseworker_feedback_form: https://docs.google.com/forms/d/e/1FAIpQLSfrUiz0oWE5jbXjPfl-idQQGPgxKplqFtcKq08UOhTaEa2k6A/viewform
  pinwheel:
    environment: <%= ENV["SANDBOX_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["SANDBOX_ARGYLE_ENVIRONMENT"] %>
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  staff_portal_enabled: true
  pilot_ended: false
  sso:
    client_id: <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id: <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "sandbox"
  pay_income_days:
    w2: 90
    gig: 90
  application_reporting_months: 2
  invitation_valid_days: 14
  weekly_report:
    recipient: ffs-eng@navapbc.com
  applicant_attributes:
    first_name:
      required: true
      redaction_type: string
    middle_name:
      redaction_type: string
    last_name:
      required: true
      redaction_type: string
    case_number:
      required: true
    date_of_birth:
      required: true
      redaction_type: date
  activity_types:
    education: true
    community_service: true
    work_programs: true
    employment: true
  prefilled_activities_enabled: true
  allowed_iframe_ancestors:
    - https://dsacms.github.io
    - https://statehub.hawaii.gov
    - https://*.statehub.hawaii.gov
# Uncomment for local testing:
#    - http://localhost:8000
#    - https://*.ngrok-free.app

- id: research
  agency_name: Example State Department of Health
  agency_contact_website: https://www.example.com/contact
  agency_missing_employers_website: https://www.example.com/contact
  agency_domain: <%= ENV["RESEARCH_DOMAIN_NAME"] %>
  caseworker_feedback_form: https://docs.google.com/forms/d/e/1FAIpQLSfrUiz0oWE5jbXjPfl-idQQGPgxKplqFtcKq08UOhTaEa2k6A/viewform # sandbox
  pinwheel:
    environment: <%= ENV["RESEARCH_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["RESEARCH_ARGYLE_ENVIRONMENT"] %>
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  staff_portal_enabled: true
  pilot_ended: false
  sso:
    client_id: <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id: <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "sandbox"
  pay_income_days:
    w2: 90
    gig: 90
  application_reporting_months: 2
  invitation_valid_days: 14
  weekly_report:
    recipient: ffs-eng@navapbc.com
  applicant_attributes:
    case_number:
      required: true
    date_of_birth:
      required: true
      redaction_type: date
  activity_types:
    education: true
    community_service: true
    work_programs: true
    employment: true

- id: accenture
  agency_name: Accenture
  agency_contact_website: https://www.example.com/contact
  agency_missing_employers_website: https://www.example.com/contact
  agency_domain: <%= ENV["ACCENTURE_DOMAIN_NAME"] %>
  pinwheel:
    environment: <%= ENV["SANDBOX_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["SANDBOX_ARGYLE_ENVIRONMENT"] %>
  transmission_method: json
  transmission_method_configuration:
    json_api_url: <%= ENV["ACCENTURE_INCOME_REPORT_URL"] %>
  application_reporting_months: 2
  invitation_valid_days: 14
  applicant_attributes:
    case_number:
      required: true
      redaction_type: string
  activity_types:
    education: true
    community_service: true
    work_programs: true
    employment: true
  allowed_iframe_ancestors:
    - https://ac1752691868225.my.salesforce-sites.com
    - https://ac1752691868225.my.salesforce.com
    - https://ac1752691868225.my.site.com
