- id: nyc
  agency_name: NYC Human Resources Administration
  agency_short_name: HRA
  agency_contact_website: https://www.nyc.gov/site/hra/help/snap-application-frequently-asked-questions.page
  caseworker_feedback_form: https://forms.office.com/r/B66WeqsBFE
  logo_path: hra_logo.png
  logo_square_path: hra_logo_square.png
  agency_demo_domain: nyc-verify-demo.navapbc.cloud
  agency_production_domain: nyc.reportmyincome.org
  pinwheel:
    environment: <%= ENV["NYC_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["SANDBOX_ARGYLE_ENVIRONMENT"] %>
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['NYC_HRA_EMAIL'] %>
  staff_portal_enabled: false
  sso:
    client_id:     <%= ENV["AZURE_NYC_DSS_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_NYC_DSS_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_NYC_DSS_TENANT_ID"] %>
    scope: "openid"
    name: "nyc_dss"
  pay_income_days: 90
  invitation_valid_days: 14
  weekly_report:
    recipient: <%= ENV['NYC_HRA_EMAIL'] %>

- id: ma
  agency_name: Department of Transitional Assistance
  agency_short_name: DTA
  agency_contact_website: https://www.mass.gov/guides/how-to-contact-dta
  caseworker_feedback_form: https://forms.office.com/r/rfV04qjG9A
  agency_demo_domain: ma-verify-demo.navapbc.cloud
  agency_production_domain: ma.reportmyincome.org
  pinwheel:
    environment: <%= ENV["MA_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["SANDBOX_ARGYLE_ENVIRONMENT"] %>
  transmission_method: s3
  transmission_method_configuration:
    bucket: <%= ENV['MA_DTA_S3_BUCKET'] %>
    public_key: <%= ENV['MA_DTA_S3_PUBLIC_KEY'].inspect %>
  staff_portal_enabled: false
  sso:
    client_id:     <%= ENV["AZURE_MA_DTA_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_MA_DTA_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_MA_DTA_TENANT_ID"] %>
    scope: "openid"
    name: "ma_dta"
  authorized_emails: <%= ENV["MA_DTA_ALLOWED_CASEWORKER_EMAILS"] %>
  pay_income_days: 90
  invitation_valid_days: 14
  logo_path: dta_logo.png
  logo_square_path: dta_logo_square.png
  weekly_report:
    recipient: <%= ENV['MA_WEEKLY_REPORT_RECIPIENTS'] %>

- id: az_des
  agency_name: Department of Economic Security
  agency_short_name: DES
  agency_contact_website: https://des.az.gov/services/basic-needs/food-assistance/contact-des
  # No caseworker feedback form since they will only be interacting with the PDFs
  # caseworker_feedback_form: null
  agency_demo_domain: az-verify-demo.navapbc.cloud
  agency_production_domain: az.reportmyincome.org
  pinwheel:
    environment: <%= ENV["AZ_DES_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["AZ_DES_ARGYLE_ENVIRONMENT"] %>
  # TODO[FFS-2628]: This will be SFTP:
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  # TODO: Disable staff portal before pilot launch
  staff_portal_enabled: true
  sso:
    client_id:     <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "az_des"
  pay_income_days: 90
  invitation_valid_days: 14
  # TODO[FFS-2629]: Get permission to use the AZ DES logo.
  # logo_path: dta_logo.png
  # logo_square_path: dta_logo_square.png
  # TODO[FFS-2649]: Enable the weekly report after pilot launch.
  # weekly_report:
  #   recipient: <%= ENV['AZ_DES_WEEKLY_REPORT_RECIPIENTS'] %>

- id: la_ldh
  agency_name: Department of Health
  agency_short_name: LDH
  agency_contact_website: https://ldh.la.gov/contact-us
  # caseworker_feedback_form: n/a
  # TODO[FFS-2689]: Add Louisiana DPH logo, these assets are not available yet.
  # logo_path: ldh_logo.png
  # logo_square_path: ldh_logo_square.png
  agency_demo_domain: la-verify-demo.navapbc.cloud
  agency_production_domain: la.reportmyincome.org
  pinwheel:
    environment: <%= ENV["LA_LDH_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["LA_LDH_ARGYLE_ENVIRONMENT"] %>
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  staff_portal_enabled: false
  # sso:
  #   client_id:     <%= ENV["AZURE_LA_LDH_CLIENT_ID"] %>
  #   client_secret: <%= ENV["AZURE_LA_LDH_CLIENT_SECRET"] %>
  #   tenant_id:     <%= ENV["AZURE_LA_LDH_TENANT_ID"] %>
  #   scope: "openid"
  #   name: "la_ldh"
  pay_income_days: 90
  invitation_valid_days: 14
  # TODO[FFS-2690]: Enable the weekly report
  # weekly_report:
  #   recipient: <%= ENV['LA_LDH_WEEKLY_REPORT_RECIPIENTS'] %>
  applicant_attributes:
    case_number:
      required: false

- id: sandbox
  agency_name: CBV Test Agency
  agency_short_name: CBV
  agency_contact_website: https://www.exampl.com/contact
  caseworker_feedback_form: https://docs.google.com/forms/d/e/1FAIpQLSfrUiz0oWE5jbXjPfl-idQQGPgxKplqFtcKq08UOhTaEa2k6A/viewform
  agency_demo_domain: sandbox-verify-demo.navapbc.cloud
  agency_production_domain: sandbox.reportmyincome.org
  pinwheel:
    environment: <%= ENV["SANDBOX_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["SANDBOX_ARGYLE_ENVIRONMENT"] %>
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  staff_portal_enabled: true
  sso:
    client_id:     <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "sandbox"
  pay_income_days: 90
  invitation_valid_days: 14
  weekly_report:
    recipient: ffs-eng@navapbc.com
  applicant_attributes:
    first_name:
      required: true
    middle_name:
      required: false
    last_name:
      required: true
    case_number:
      required: true
