- id: az_des
  agency_name: Department of Economic Security/Family Assistance Administration
  agency_contact_website: https://myfamilybenefits.azdes.gov/
  agency_domain: <%= ENV["AZ_DES_DOMAIN_NAME"] %>
  # No caseworker feedback form since they will only be interacting with the PDFs
  # caseworker_feedback_form: null
  pinwheel:
    environment: <%= ENV["AZ_DES_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["AZ_DES_ARGYLE_ENVIRONMENT"] %>
  transmission_method: sftp
  transmission_method_configuration:
    user: <%= ENV['AZ_DES_SFTP_USER'] %>
    password: <%= ENV['AZ_DES_SFTP_PASSWORD'] %>
    url: <%= ENV['AZ_DES_SFTP_URL'] %>
    sftp_directory: <%= ENV['AZ_DES_SFTP_DIRECTORY'] %>
    csv_summary_reports_enabled: false
  staff_portal_enabled: false
  pilot_ended: false
  generic_links_disabled: true
  sso:
    client_id:     <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "az_des"
  pay_income_days:
    w2: 90
    gig: 182
  invitation_valid_days: 10
  allow_invitation_reuse: true
  logo_path: des_logo.png
  weekly_report:
    recipient: <%= ENV['AZ_DES_WEEKLY_REPORT_RECIPIENTS'] %>
    report_variant: invitations

- id: la_ldh
  agency_name: Department of Health
  agency_contact_website: https://ldh.la.gov/renew-medicaid
  agency_domain: <%= ENV["LA_LDH_DOMAIN_NAME"] %>
  # caseworker_feedback_form: n/a
  logo_path: ldh_logo.svg
  default_origin: sms
  pinwheel:
    environment: <%= ENV["LA_LDH_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["LA_LDH_ARGYLE_ENVIRONMENT"] %>
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['LA_LDH_EMAIL'] %>
  staff_portal_enabled: false
  pilot_ended: <%= ENV["LA_LDH_PILOT_ENABLED"] != "true" %>
  # sso:
  #   client_id:     <%= ENV["AZURE_LA_LDH_CLIENT_ID"] %>
  #   client_secret: <%= ENV["AZURE_LA_LDH_CLIENT_SECRET"] %>
  #   tenant_id:     <%= ENV["AZURE_LA_LDH_TENANT_ID"] %>
  #   scope: "openid"
  #   name: "la_ldh"
  pay_income_days:
    w2: 90
    gig: 90
  invitation_valid_days: 14
  weekly_report:
    recipient: <%= ENV['LA_LDH_WEEKLY_REPORT_RECIPIENTS'] %>
    report_variant: flows
  applicant_attributes:
    case_number:
      required: false
    date_of_birth:
      required: true

- id: sandbox
  agency_name: CBV Test Agency
  agency_contact_website: https://www.example.com/contact
  agency_domain: <%= ENV["SANDBOX_DOMAIN_NAME"] %>
  caseworker_feedback_form: https://forms.gle/Qb7D12kHZymur5jKA
  pinwheel:
    environment: <%= ENV["SANDBOX_PINWHEEL_ENVIRONMENT"] %>
  argyle:
    environment: <%= ENV["SANDBOX_ARGYLE_ENVIRONMENT"] %>
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  staff_portal_enabled: true
  pilot_ended: false
  sso:
    client_id:     <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "sandbox"
  pay_income_days:
    w2: 90
    gig: 90
  invitation_valid_days: 14
  allow_invitation_reuse: true
  weekly_report:
    recipient: ffs-eng@navapbc.com
  applicant_attributes:
    first_name:
      required: true
    middle_name:
      required: false
    last_name:
      required: true
    case_number:
      required: true
    date_of_birth:
      required: true
