# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en
## All available locales are inferred from the data by default. Alternatively, specify them explicitly:
# locales: [es, fr]
## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `Find.find` patterns where translations are read from:
  read:
    ## Default:
    # - config/locales/%{locale}.yml
    ## More files:
    # - config/locales/**/*.%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    ## For example, write devise and simple form keys to their respective files:
    # - ['{devise, simple_form}.*', 'config/locales/\1.%{locale}.yml']
    ## Catch-all default:
    # - config/locales/%{locale}.yml

  # External locale data (e.g. gems).
  # This data is not considered unused and is never written to.
  external:
    ## Example (replace %#= with %=):
    # - "<%#= %x[bundle info vagrant --path].chomp %>/templates/locales/%{locale}.yml"

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: conservative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `Find.find` patterns to search in:
  # paths:
  #  - app/

  ## Root directories for relative keys resolution.
  # relative_roots:
  #   - app/controllers
  #   - app/helpers
  #   - app/mailers
  #   - app/presenters
  #   - app/views

  ## Directories where method names which should not be part of a relative key resolution.
  # By default, if a relative translation is used inside a method, the name of the method will be considered part of the resolved key.
  # Directories listed here will not consider the name of the method part of the resolved key
  #
  # relative_exclude_method_name_paths:
  #  -

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   *.jpg *.jpeg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less
  ##   *.yml *.json *.zip *.tar.gz *.swf *.flv *.mp3 *.wav *.flac *.webm *.mp4 *.ogg *.opus *.webp *.map *.xlsx
  exclude:
    - app/assets/images
    - app/assets/fonts
    - app/assets/videos
    - app/assets/builds

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  # strict: true

  ## Allows adding ast_matchers for finding translations using the AST-scanners
  ## The available matchers are:
  ## - RailsModelMatcher
  ##     Matches ActiveRecord translations like
  ##     User.human_attribute_name(:email) and User.model_name.human
  ##
  ## To implement your own, please see `I18n::Tasks::Scanners::AstMatchers::BaseMatcher`.
  # <%# I18n::Tasks.add_ast_matcher('I18n::Tasks::Scanners::AstMatchers::RailsModelMatcher') %>

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Translation Services
# translation:
#   # Google Translate
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   google_translate_api_key: "AbC-dEf5"
#   # DeepL Pro Translate
#   # Get an API key and subscription at https://www.deepl.com/pro to use DeepL Pro
#   deepl_api_key: "48E92789-57A3-466A-9959-1A1A1A1A1A1A"
#   # deepl_host: "https://api.deepl.com"
#   # deepl_version: "v2"
#   # add additional options to the DeepL.translate call: https://www.deepl.com/docs-api/translate-text/translate-text/
#   deepl_options:
#     formality: prefer_less
## Do not consider these keys missing:
ignore_missing:
  all:
    - 'shared.languages.*'
    - 'shared.header.{title,close,demo_banner,menu}'
  en:
    - "date.*"    # Defaults provided by rails-i18n
    - "time.*"    # Defaults provided by rails-i18n
    - "payment_frequencies.*"   # Helper method uses English values directly
  es:
    # Caseworker pages that are only supported in English:
    - "caseworker.cbv_flow_invitations.*"
    - "caseworker.dashboards.*"
    - "caseworker.entries.*"
    # Caseworker emails that are only supported in English:
    - "activerecord.errors.models.cbv_flow_invitation.*"
    - "activerecord.errors.models.cbv_applicant*"
    - "caseworker_mailer.summary_email.*"
    # Caseworker PDF strings that are only supported in English:
    - "cbv.submits.show.pdf.caseworker.*"

    # Currently awaiting translation:
    # - "example.strings.*"   # Tag with ticket number that created or modified the string
    - "cbv.summaries.show.description"                    # FFS-2562
    - "cbv.summaries.show.header"                         # FFS-2494
    - "aggregator_strings.deductions.401k"                # FFS-2723
    - "aggregator_strings.deductions.dental"              # FFS-2723
    - "aggregator_strings.deductions.garnishment"         # FFS-2723
    - "aggregator_strings.deductions.other"               # FFS-2723
    - "aggregator_strings.deductions.vision"              # FFS-2723
    - "aggregator_strings.earnings_category.base"         # FFS-2723
    - "aggregator_strings.earnings_category.benefits"     # FFS-2723
    - "aggregator_strings.employment_statuses.inactive"   # FFS-2723
    - "aggregator_strings.employment_statuses.terminated" # FFS-2723
    - "aggregator_strings.payment_frequencies.quarterly"  # FFS-2723
    - "aggregator_strings.deductions.roth"                # FFS-2723

    # AZ DES (FFS-2648)
    - "shared.agency_full_name.az_des"
    - "shared.agency_acronym.az_des"
    - "shared.benefit.az_des"
    - "shared.reporting_purpose.az_des"

    # AZ DES submit (FFS-2648)
    - "cbv.submits.show.warning_1"
    - "cbv.submits.show.consent_checkbox_label_html.az_des"

    # LA LDH (FFS-2668)
    - "shared.agency_full_name.la_ldh"
    - "shared.benefit.la_ldh"
    - "shared.header.cbv_flow_title.la_ldh"
    - "shared.header.preheader.la_ldh"
    - "shared.agency_acronym.la_ldh"
    - "shared.reporting_purpose.la_ldh"

    # LA employer_search (FFS-2688)
    - "cbv.employer_searches.show.can_not_find_employer"
    - "cbv.employer_searches.show.to_continue_li_3_continue"

    # LA add_jobs (FFS-2688)
    - "cbv.add_jobs.show.answer_yes_bullet_1"
    - "cbv.add_jobs.show.answer_yes_bullet_2"

    # LA expired (FFS-2688)
    - "cbv.expired_invitations.show.cta_button_html.la_ldh"

    # LA maintenance (FFS-2688)
    - "maintenance.body_1"
    - "maintenance.body_2"
    - "maintenance.header"
    - "shared.pilot_name"

    # LA missing_results (FFS-2688)
    - "cbv.missing_results.show.exit_button_html.la_ldh"
    - "cbv.missing_results.show.not_listed_p2"
    - "cbv.missing_results.show.not_listed_p2_link_html.la_ldh"
    - "cbv.missing_results.show.not_listed_p2_link_html.sandbox"

    # LA submit (FFS-2688)
    - "cbv.submits.show.consent_checkbox_label_html.default"

    # LA success (FFS-2688)
    - "cbv.successes.show.follow_up"
    - "cbv.successes.show.if_it_didnt_work"

    # LA applicant_information (FFS-2688)
    - "cbv.applicant_informations.la_ldh.fields.case_number.blank"
    - "cbv.applicant_informations.la_ldh.fields.case_number.help_text"
    - "cbv.applicant_informations.la_ldh.fields.case_number.prompt"
    - "cbv.applicant_informations.la_ldh.fields.case_number.super_one_html"

    # LA applicant_information errors (FFS-2773)
    - "cbv.applicant_informations.la_ldh.fields.date_of_birth.blank"
    - "cbv.applicant_informations.la_ldh.fields.date_of_birth.prompt"
    - "cbv.applicant_informations.la_ldh.fields.date_of_birth.super_one_html"
    - "cbv.applicant_informations.la_ldh.fields.date_of_birth.help_text"
    - "cbv.applicant_informations.sandbox.fields.date_of_birth.blank"
    - "cbv.applicant_informations.sandbox.fields.date_of_birth.prompt"
    - "cbv.applicant_informations.sandbox.fields.date_of_birth.super_one_html"
    - "cbv.applicant_informations.sandbox.fields.date_of_birth.help_text"

    # LA welcome (FFS-2688)
    - "pages.home.description_1"
    - "pages.home.description_2"
    - "pages.home.description_3"
    - "pages.home.header"

    # LA client_pdf (FFS-2688)
    - "aggregator_strings.payment_frequencies.annual"
    - "aggregator_strings.payment_frequencies.annually"
    - "cbv.payment_details.show.employment_end_date"
    - "cbv.submits.show.application_or_recertification_date.la_ldh"
    - "cbv.submits.show.none_found"

    # LA payment_details (FFS-2688)
    - "cbv.payment_details.show.number_of_hours_worked"
    - "cbv.payment_details.show.pay_frequency"
    - "cbv.payment_details.show.subheader.la_ldh"

    # LA help (FFS-2688)
    - "help.alert.heading"
    - "help.alert.help_options"
    - "help.show.credentials.step2.content"
    - "help.show.credentials.step3.content"
    - "help.show.employer.step1.title"
    - "help.show.employer.step3.content"
    - "help.show.provider.step3.content"

    # LA employer_search (FFS-2688)
    - "cbv.employer_searches.show.header"
    - "cbv.employer_searches.show.search_label_2"
    - "cbv.employer_searches.show.search_label_html"

    # LA entry (FFS-2688)
    - "cbv.entries.show.checkbox.default"
    - "cbv.entries.show.subheader_html"
    - "cbv.entries.show.what_if_i_cant_use_this_body_1"
    - "cbv.entries.show.what_if_i_cant_use_this_body_2_html.default"
    - "cbv.entries.show.what_if_i_cant_use_this_body_2_html.la_ldh"
    - "cbv.entries.show.what_if_i_cant_use_this_title"
    - "cbv.entries.show.who_is_this_for_body"
    - "cbv.entries.show.who_is_this_for_title"

    # LA summary (FFS-2688)
    - "cbv.summaries.show.application_information"
    - "cbv.summaries.show.total_income_from"
    - "cbv.summaries.show.total_payments_desc"

    # LA fixes (FFS-2688)
    - "cbv.applicant_informations.show.explanation"
    - "cbv.employer_searches.show.exit_button_text"

    # LA fixes-2 (FFS-2688)
    - "cbv.summaries.show.must_match.default"
    - "cbv.summaries.show.must_match.la_ldh"

    # AZ (FFS-XXXX)
    - "cbv.successes.show.copy_link"
    - "cbv.successes.show.copied_link"
    - "cbv.successes.show.share_invitation_link_content"
    - "cbv.successes.show.share_invitation_link_title"
    - "cbv.successes.show.whats_next"
    - "cbv.successes.show.whats_next_1_title"
    - "cbv.successes.show.whats_next_1_li_1"
    - "cbv.successes.show.whats_next_1_li_2"
    - "cbv.successes.show.whats_next_2_title"
    - "cbv.successes.show.whats_next_2_li_1"

## Consider these keys used:
ignore_unused:
  all:
    - "*.{nyc,ma,sandbox,az_des,la_ldh,default}"       # site-specific translations
    - "activerecord.errors.*"                   # model errors are not always explicitly used
    - "date.*"                                  # date formats are not always explicitly used
    - "time.*"                                  # time formats are not always explicitly used
    - "aggregator_strings.*"                    # dynamically looked up aggregator translations
    - "help.show.*.intro"                       # dynamically looked up help translations
    - "help.show.credentials.security_message"  # dynamically looked up help translations

## Unused examples of how to use this file:

## Exclude these keys from the `i18n-tasks eq-base' report:
# ignore_eq_base:
#   all:
#     - common.ok
#   fr,es:
#     - common.brand

## Exclude these keys from the `i18n-tasks check-consistent-interpolations` report:
# ignore_inconsistent_interpolations:
# - 'activerecord.attributes.*'

## Ignore these keys completely:
# ignore:
#  - kaminari.*

## Sometimes, it isn't possible for i18n-tasks to match the key correctly,
## e.g. in case of a relative key defined in a helper method.
## In these cases you can use the built-in PatternMapper to map patterns to keys, e.g.:
#
# <%# I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper',
#       only: %w(*.html.haml *.html.slim),
#       patterns: [['= title\b', '.page_title']] %>
#
# The PatternMapper can also match key literals via a special %{key} interpolation, e.g.:
#
# <%# I18n::Tasks.add_scanner 'I18n::Tasks::Scanners::PatternMapper',
#       patterns: [['\bSpree\.t[( ]\s*%{key}', 'spree.%{key}']] %>
