production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  record_newrelic_queue_metrics:
    class: RecordBatchedNewrelicMetricsJob
    schedule: every minute