- id: nyc
  agency_name: NYC Human Resources Administration
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_DEVELOPMENT'] %>
    environment: development
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['NYC_HRA_EMAIL'] %>
  sso:
    client_id:     <%= ENV["AZURE_NYC_DSS_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_NYC_DSS_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_NYC_DSS_TENANT_ID"] %>
    scope: "openid"
    name: "nyc_dss"
  learn_more_link_text: Learn more on nyc.gov
  learn_more_link_url: https://www.nyc.gov/site/hra/help/snap-application-frequently-asked-questions.page
- id: ma
  agency_name: Massachusetts Department of Transitional Assistance
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_DEVELOPMENT'] %>
    environment: development
  transmission_method: null
  transmission_method_configuration: {}
  sso:
    client_id:     <%= ENV["AZURE_MA_DTA_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_MA_DTA_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_MA_DTA_TENANT_ID"] %>
    scope: "openid"
    name: "ma_dta"
  learn_more_link_text: Learn more at Mass.gov
  learn_more_link_url: https://www.mass.gov/guides/how-to-contact-dta
- id: sandbox
  agency_name: CBV Test Agency
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_SANDBOX'] %>
    environment: sandbox
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  sso:
    client_id:     <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "sandbox"
  learn_more_link_text: Learn more at CBV Test Agency
  learn_more_link_url: https://www.mass.gov/guides/how-to-contact-dta
