- id: nyc
  agency_name: NYC Human Resources Administration
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_DEVELOPMENT'] %>
    environment: development
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['NYC_HRA_EMAIL'] %>
  agency_short_name: HRA
  sso:
    client_id:     <%= ENV["AZURE_NYC_DSS_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_NYC_DSS_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_NYC_DSS_TENANT_ID"] %>
    scope: "openid"
    name: "nyc_dss"
  pay_income_days: 90
  invitation_valid_days: 14
- id: ma
  agency_name: Department of Transitional Assistance
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_DEVELOPMENT'] %>
    environment: development
  transmission_method: null
  transmission_method_configuration: {}
  agency_short_name: DTA
  sso:
    client_id:     <%= ENV["AZURE_MA_DTA_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_MA_DTA_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_MA_DTA_TENANT_ID"] %>
    scope: "openid"
    name: "ma_dta"
  pay_income_days: 90
  invitation_valid_days: 14
  logo_path: dta_logo.png
  logo_square_path: dta_logo_square.avif
- id: sandbox
  agency_name: CBV Test Agency
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_SANDBOX'] %>
    environment: sandbox
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  agency_short_name: CBV
  sso:
    client_id:     <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
    client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
    tenant_id:     <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
    scope: "openid"
    name: "sandbox"
  pay_income_days: 90
  invitation_valid_days: 14
