- id: nyc
  agency_name: NYC Human Resources Administration
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_DEVELOPMENT'] %>
    environment: development
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['NYC_HRA_EMAIL'] %>
  agency_short_name: HRA
  agency_help_link: https://www.nyc.gov/site/hra/help/snap-application-frequently-asked-questions.page
- id: ma
  agency_name: Massachusetts Department of Transitional Assistance
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_DEVELOPMENT'] %>
    environment: development
  transmission_method: null
  transmission_method_configuration: {}
  agency_short_name: DTA
  agency_help_link: https://www.mass.gov/guides/how-to-contact-dta
- id: sandbox
  agency_name: CBV Test Agency
  pinwheel:
    api_token: <%= ENV['PINWHEEL_API_TOKEN_SANDBOX'] %>
    environment: sandbox
  transmission_method: shared_email
  transmission_method_configuration:
    email: <%= ENV['SLACK_TEST_EMAIL'] %>
  agency_short_name: CBV Agency Dept of Helping
  agency_help_link: https://example.com/dept-of-helping
