# action.yml file for a custom composite action
name: 'Remove Debug Gems'
description: 'Removes debug-related gems from the Gemfile'
runs:
  using: 'composite'
  steps:
    - name: Remove Debug Gems
      shell: bash
      run: |
        sed -i '/debase-ruby_core_source/d' ./Gemfile
        sed -i '/debase/d' ./Gemfile
        sed -i '/ruby-debug-ide/d' ./Gemfile
        bundle install
        bundle lock --add-platform x86_64-linux
