# action.yml file for a custom composite action
name: 'Remove Debug Gems'
description: 'Removes debug-related gems from the Gemfile'
defaults:
  run:
    working-directory: ./app
runs:
  using: 'composite'
  steps:
    - name: Remove Debug Gems
      shell: bash
      run: |
        sed -i '/debase-ruby_core_source/d' ./app/Gemfile
        sed -i '/debase/d' ./app/Gemfile
        sed -i '/ruby-debug-ide/d' ./app/Gemfile
