name: Cleanup Gemfile and remove and debug gems

on:
  push: # Trigger on push to any branch
  pull_request: # Trigger on pull requests to any branch

jobs:
  clean_gemfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove Debug Gems from Gemfile
        run: |
          sed -i '/debase-ruby_core_source/d' ./Gemfile
          sed -i '/debase/d' ./Gemfile
          sed -i '/ruby-debug-ide/d' ./Gemfile
