version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
  percyCSS: |
    *,
    *::before,
    *::after {
      animation-duration: 0s !important;
      animation-delay: 0s !important;
      transition-duration: 0s !important;
      transition-delay: 0s !important;
    }
discovery:
  networkIdleTimeout: 250
  disallowedHostnames:
    - bam.nr-data.net
