source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }


ruby "3.4.5"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.2"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"


# as of ruby 3.4, csv is no longer a default gem
gem "csv"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.6"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 7.2.0"

# Bundle and transpile JavaScript [https://github.com/rails/jsbundling-rails]
gem "jsbundling-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Bundle and process CSS [https://github.com/rails/cssbundling-rails]
gem "cssbundling-rails"
gem "premailer-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
gem "redis", "~> 5.4"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "device_detector"

# Used to generate mock identity data in all environments
gem "faker", "~> 3.6"

# Use Sass to process CSS
# gem "sassc-rails"

gem "mixpanel-ruby"
gem "newrelic_rpm"
gem "rails_semantic_logger", require: false

gem "solid_queue", ">= 0.3.0"
# dashboard to manage solid queue
gem "mission_control-jobs"


gem "faraday", "~> 2.14.1"

gem "wicked_pdf"
gem "actioncable-enhanced-postgresql-adapter"
gem "aws-sdk-rails"
gem "aws-sdk-s3"
gem "aws-actionmailer-ses"

# profiling
gem "rack-mini-profiler"
gem "stackprof"

# https://www.ruby-lang.org/en/news/2024/08/01/dos-rexml-cve-2024-41123/
gem "rexml", "~> 3.4.2"
gem "gpgme", "~> 2.0"
gem "pdf-reader", "~> 2.15.1"
gem "net-imap", "0.6.2"   # Fixing GHSA-j3g3-5qv5-52m
gem "cgi", ">= 0.4.2"     # Fixing GHSA-mhwm-jh88-3gjf
gem "thor", ">= 1.4.0"    # Fixing GHSA-mqcp-p2hv-vw6x

group :development, :test do
  gem "brakeman"
  gem "bundler-audit", "~> 0.9"
  gem "capybara"
  gem "debug", platforms: %i[mri windows]
  gem "dotenv-rails", "~> 3.2"
  gem "erb_lint", require: false
  gem "i18n-tasks", "~> 1.1", require: false
  gem "rspec-rails", "~> 8.0"
  gem "rubocop"
  gem "rubocop-rspec"
  gem "rubocop-rails-omakase"
  gem "selenium-webdriver", ">= 4.26.0"
  gem "timecop"
  gem "mutex_m"
end

group :development do
  gem "debase-ruby_core_source", "~> 4.0"
  gem "debase", "~> 0.2.9", require: false
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
  gem "rails-erd", "~> 1.7"
end

group :test do
  gem "axe-core-rspec", "~> 4.11"
  gem "climate_control", "~> 1.0"
  gem "webmock", ">= 3.24.0"
  gem "factory_bot", "~> 6.5"
  gem "rails-controller-testing"
  gem "vcr"
end

group :production do
  # Add plugin for pg gem to support AWS RDS IAM
  gem "pg-aws_rds_iam", "~> 0.7.0"
end
gem "devise", "~> 4.9"

gem "view_component"
gem "lookbook"
gem "wkhtmltopdf-binary"

gem "net-sftp"
gem "net-ssh"

# Sinatra for JSON API reference implementation
gem "sinatra", "~> 4.2"

gem "pry", "~> 0.16.0", group: :development
gem "pry-doc", "~> 1.7", group: :development
