D = Steep::Diagnostic

target :app do
  signature "sig"

  check 'lib'
  check 'app'
  check 'Gemfile'

  ignore 'spec/*.rb'

  configure_code_diagnostics(D::Ruby.strict)

  configure_code_diagnostics do |hash|
    hash[D::Ruby::NoMethod] = :information
  end
end
