// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CbvEmployerSearch from "./cbv/employer_search"
application.register("cbv-employer-search", CbvEmployerSearch)

import CbvAddJob from "./cbv/add_job"
application.register("cbv-add-job", CbvAddJob)