id: az_des
active: <%= ENV["AGENCY_AZ_DES_ACTIVE"] %>
agency_name: Department of Economic Security/Family Assistance Administration
agency_contact_website: https://myfamilybenefits.azdes.gov/
agency_domain: "az"
# No caseworker feedback form since they will only be interacting with the PDFs
# caseworker_feedback_form: null
pinwheel:
  environment: <%= ENV["AZ_DES_PINWHEEL_ENVIRONMENT"] %>
argyle:
  environment: <%= ENV["AZ_DES_ARGYLE_ENVIRONMENT"] %>
transmission_method: sftp
transmission_method_configuration:
  user: <%= ENV['AZ_DES_SFTP_USER'] %>
  password: <%= ENV['AZ_DES_SFTP_PASSWORD'] %>
  url: <%= ENV['AZ_DES_SFTP_URL'] %>
  sftp_directory: <%= ENV['AZ_DES_SFTP_DIRECTORY'] %>
  # this controls if daily csv summaries are sent to configured SFTP
  csv_summary_reports_enabled: false
staff_portal_enabled: false
pilot_ended: false
generic_links_disabled: true
sso:
  client_id:     <%= ENV["AZURE_SANDBOX_CLIENT_ID"] %>
  client_secret: <%= ENV["AZURE_SANDBOX_CLIENT_SECRET"] %>
  tenant_id:     <%= ENV["AZURE_SANDBOX_TENANT_ID"] %>
  scope: "openid"
  name: "az_des"
pay_income_days:
  w2: 90
  gig: 182
invitation_valid_days: 10
allow_invitation_reuse: true
logo_path: des_logo.png
weekly_report:
  recipient: <%= ENV['AZ_DES_WEEKLY_REPORT_RECIPIENTS'] %>
  report_variant: invitations
