interface _RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> String
  def preview_view_components_path: (*untyped) -> String
  def preview_view_component_path: (*untyped) -> String
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def user_az_des_omniauth_authorize_path: (*untyped) -> String
  def user_az_des_omniauth_callback_path: (*untyped) -> String
  def user_sandbox_omniauth_authorize_path: (*untyped) -> String
  def user_sandbox_omniauth_callback_path: (*untyped) -> String
  def destroy_user_session_path: (*untyped) -> String
  def root_path: (*untyped) -> String
  def health_path: (*untyped) -> String
  def health_test_queueing_path: (*untyped) -> String
  def health_test_rendering_path: (*untyped) -> String
  def help_path: (*untyped) -> String
  def help_topic_path: (*untyped) -> String
  def maintenance_path: (*untyped) -> String
  def feedbacks_path: (*untyped) -> String
  def start_path: (*untyped) -> String
  def start_flow_path: (*untyped) -> String
  def cbv_flow_entry_path: (*untyped) -> String
  def cbv_flow_employer_search_path: (*untyped) -> String
  def cbv_flow_synchronizations_path: (*untyped) -> String
  def cbv_flow_synchronization_failures_path: (*untyped) -> String
  def cbv_flow_summary_path: (*untyped) -> String
  def cbv_flow_submit_path: (*untyped) -> String
  def cbv_flow_missing_results_path: (*untyped) -> String
  def cbv_flow_success_path: (*untyped) -> String
  def cbv_flow_add_job_path: (*untyped) -> String
  def cbv_flow_other_job_path: (*untyped) -> String
  def cbv_flow_payment_details_path: (*untyped) -> String
  def cbv_flow_expired_invitation_path: (*untyped) -> String
  def cbv_flow_applicant_information_path: (*untyped) -> String
  def cbv_flow_new_path: (*untyped) -> String
  def cbv_flow_session_refresh_path: (*untyped) -> String
  def cbv_flow_session_end_path: (*untyped) -> String
  def sso_path: (*untyped) -> String
  def new_user_session_path: (*untyped) -> String
  def caseworker_dashboard_path: (*untyped) -> String
  def invitations_path: (*untyped) -> String
  def new_invitation_path: (*untyped) -> String
  def webhooks_pinwheel_events_path: (*untyped) -> String
  def webhooks_argyle_events_path: (*untyped) -> String
  def api_invitations_path: (*untyped) -> String
  def api_tokens_path: (*untyped) -> String
  def api_user_action_path: (*untyped) -> String
  def mission_control_jobs_path: (*untyped) -> String
  def turbo_recede_historical_location_path: (*untyped) -> String
  def turbo_resume_historical_location_path: (*untyped) -> String
  def turbo_refresh_historical_location_path: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def preview_view_components_url: (*untyped) -> String
  def preview_view_component_url: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def user_az_des_omniauth_authorize_url: (*untyped) -> String
  def user_az_des_omniauth_callback_url: (*untyped) -> String
  def user_sandbox_omniauth_authorize_url: (*untyped) -> String
  def user_sandbox_omniauth_callback_url: (*untyped) -> String
  def destroy_user_session_url: (*untyped) -> String
  def root_url: (*untyped) -> String
  def health_url: (*untyped) -> String
  def health_test_queueing_url: (*untyped) -> String
  def health_test_rendering_url: (*untyped) -> String
  def help_url: (*untyped) -> String
  def help_topic_url: (*untyped) -> String
  def maintenance_url: (*untyped) -> String
  def feedbacks_url: (*untyped) -> String
  def start_url: (*untyped) -> String
  def start_flow_url: (*untyped) -> String
  def cbv_flow_entry_url: (*untyped) -> String
  def cbv_flow_employer_search_url: (*untyped) -> String
  def cbv_flow_synchronizations_url: (*untyped) -> String
  def cbv_flow_synchronization_failures_url: (*untyped) -> String
  def cbv_flow_summary_url: (*untyped) -> String
  def cbv_flow_submit_url: (*untyped) -> String
  def cbv_flow_missing_results_url: (*untyped) -> String
  def cbv_flow_success_url: (*untyped) -> String
  def cbv_flow_add_job_url: (*untyped) -> String
  def cbv_flow_other_job_url: (*untyped) -> String
  def cbv_flow_payment_details_url: (*untyped) -> String
  def cbv_flow_expired_invitation_url: (*untyped) -> String
  def cbv_flow_applicant_information_url: (*untyped) -> String
  def cbv_flow_new_url: (*untyped) -> String
  def cbv_flow_session_refresh_url: (*untyped) -> String
  def cbv_flow_session_end_url: (*untyped) -> String
  def sso_url: (*untyped) -> String
  def new_user_session_url: (*untyped) -> String
  def caseworker_dashboard_url: (*untyped) -> String
  def invitations_url: (*untyped) -> String
  def new_invitation_url: (*untyped) -> String
  def webhooks_pinwheel_events_url: (*untyped) -> String
  def webhooks_argyle_events_url: (*untyped) -> String
  def api_invitations_url: (*untyped) -> String
  def api_tokens_url: (*untyped) -> String
  def api_user_action_url: (*untyped) -> String
  def mission_control_jobs_url: (*untyped) -> String
  def turbo_recede_historical_location_url: (*untyped) -> String
  def turbo_resume_historical_location_url: (*untyped) -> String
  def turbo_refresh_historical_location_url: (*untyped) -> String
end
