name: CI Documentation Checks

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This is the GitHub Actions-friendly port of the linter used in the Makefile.
      - uses: tcort/github-action-markdown-link-check@1.1.0
        with:
          use-quiet-mode: "yes" # errors only.
          config-file: ".github/workflows/markdownlint-config.json"
