name: Build and publish
run-name: Build and publish ${{ inputs.app_name }}:${{ inputs.ref }}

on:
  workflow_call:
    inputs:
      app_name:
        description: "name of application folder under infra directory"
        required: true
        type: string
      ref:
        description: The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, use branch or tag that triggered the workflow run.
        required: true
        type: string
  workflow_dispatch:
    inputs:
      app_name:
        description: "name of application folder under infra directory"
        required: true
        type: string
      ref:
        description: The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, use branch or tag that triggered the workflow run.
        required: true
        type: string

jobs:
  get-commit-hash:
    name: Get commit hash
    if: github.repository_owner == 'CMSgov'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      commit_hash: ${{ steps.get-commit-hash.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Get commit hash
        id: get-commit-hash
        run: |
          COMMIT_HASH=$(git rev-parse ${{ inputs.ref }})
          echo "Commit hash: $COMMIT_HASH"
          echo "commit_hash=$COMMIT_HASH" >> "$GITHUB_OUTPUT"

  build-and-publish:
    name: Build and publish
    if: github.repository_owner == 'CMSgov'
    runs-on: ubuntu-latest
    needs: get-commit-hash
    concurrency: ${{ github.workflow }}-${{ needs.get-commit-hash.outputs.commit_hash }}

    permissions:
      contents: read

    env:
      IMAGE_REPOSITORY_URL: artifactory.cloud.cms.gov/emmy-docker/emmy-app

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: artifactory.cloud.cms.gov
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Get image metadata
        id: image-metadata
        run: |
          image_name=$(make APP_NAME=${{ inputs.app_name }} release-image-name)
          image_tag=$(make release-image-tag)
          echo "image_name=$image_name" >> "$GITHUB_OUTPUT"
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"

      - name: Check if image is already published
        id: check-image-published
        env:
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        run: |
          is_image_published=$(./bin/is-artifactory-image-published "${{ steps.image-metadata.outputs.image_tag }}")
          echo "Is image published: $is_image_published"
          echo "is_image_published=$is_image_published" >> "$GITHUB_OUTPUT"

      - name: Build release
        if: steps.check-image-published.outputs.is_image_published == 'false'
        run: make APP_NAME=${{ inputs.app_name }} release-build

      - name: Publish release
        if: steps.check-image-published.outputs.is_image_published == 'false'
        run: |
          docker tag "${{ steps.image-metadata.outputs.image_name }}:${{ steps.image-metadata.outputs.image_tag }}" "${IMAGE_REPOSITORY_URL}:${{ steps.image-metadata.outputs.image_tag }}"
          docker push "${IMAGE_REPOSITORY_URL}:${{ steps.image-metadata.outputs.image_tag }}"
