name: Ruby and Javascript dependency scans

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'app/doc/**'
      - 'app/README.md'
  pull_request:
    branches: [ main ]
    paths: ['app/**']
  schedule:
    # cron format: 'minute hour dayofmonth month dayofweek'
    # this will run at noon UTC every day (7am EST / 8am EDT)
    - cron: '0 12 * * *'

jobs:
  bundle-audit:
    name: Bundle audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-languages

      - name: Update advisory database and run checks
        run: bundle exec rake bundler:audit
        working-directory: app

  npm-audit:
    name: npm audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-languages

      - name: Run npm audit
        run: bundle exec rake npm:audit
        working-directory: app

  ruby-bom:
    name: Ruby SBOM Generation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-languages
      - name: Install cyclonedx
        run: gem install cyclonedx-ruby
      - name: Generate BOM
        working-directory: app
        run: cyclonedx-ruby -p . -o ruby_bom.xml
      - name: Save BOM
        working-directory: app
        uses: actions/upload-artifact@v3
        with:
          name: ruby-bom
          path: ./ruby_bom.xml
