name: Check i18n-tasks health

on:
  pull_request:
    paths:
      - 'app/**'
  push:
    branches:
      - main
      - develop

jobs:
  i18n_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Ruby & Javascript
      uses: ./.github/actions/setup-languages

    - name: Run i18n-tasks health check
      run: |
        bundle exec i18n-tasks health
      working-directory: ./app
