name: OWASP ZAP scan

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  owasp-scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: iv_cbv_payroll_test
          POSTGRES_USER: cidbuser
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/actions/setup-project

      - uses: ./.github/actions/run-server
        with:
          database_url: ${{ steps.setup.outputs.database_url }}

      - name: Run OWASP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-weekly'
          target: 'http://localhost:3000/'
          fail_action: true
          rules_file_name: 'zap.conf'
          cmd_options: '-I'
