name: rspec tests

on: [pull_request]

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: iv_cbv_payroll_test
          POSTGRES_USER: cidbuser
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/actions/setup-project
        with:
          rails_env: test

      - name: Set RAILS_MASTER_KEY from file
        id: set-rails-master-key
        run: echo "RAILS_MASTER_KEY=$(cat ./.config/credentials/test.key)" >> $GITHUB_ENV

      - name: Run rspec
        env:
          DATABASE_URL: ${{ steps.setup.outputs.database_url }}
        run: bundle exec rspec
