name: Rubocop style checks

on:
  pull_request:
    paths: ['app/**']

jobs:
  rspec:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby & Javascript
        uses: ./.github/actions/setup-languages
      - name: Run Rubocop
        working-directory: app
        run: bundle exec rubocop
